config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),  # путь до приложения main
                  path('clients/', include('clients.urls', namespace='clients')),  # путь до приложения clients
                  path('mailing/', include('mailing.urls', namespace='mailing')),  # путь до приложения mailing
                  path('users/', include('users.urls', namespace='users')),  # путь до приложения users
                  path('vlog/', include('vlog.urls', namespace='vlog')),  # путь до приложения vlog
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path


from mailing.apps import MailingConfig
from mailing.views import MessageListView, MessageCreateView, MessageUpdateView, MessageDetailView, MessageDeleteView, \
    MailingListView, MailingCreateView, MailingDetailView, MailingUpdateView, MailingDeleteView, LogListView, \
    LogDetailView

app_name = MailingConfig.name


urlpatterns = [
    path('message_list/', MessageListView.as_view(), name='message_list'),  # список сообщений
    path('message_detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),  # просмотр сообщения
    path('message_create/', MessageCreateView.as_view(), name='message_create'),  # создание сообщения
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),  # редактирование сообщения
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),  # удаление сообщения
    # path('message_publish/<int:pk>/toggle_publish/', toggle_publish, name='toggle_publish'),  # публикация сообщения

    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),  # список рассылок
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),  # просмотр рассылки
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),  # создание рассылки
    path('mailing_edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),  # редактирование рассылки
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),  # удаление рассылки

    path('log_list/', LogListView.as_view(), name='log_list'),  # список логов
    path('log_detail/<int:pk>/', LogDetailView.as_view(), name='log_detail'),  # просмотр лога

]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexView

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Главная
]

mailing/models.py
from datetime import datetime

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from clients.models import Client

NULLABLE = {'null': True, 'blank': True}


class Message(models.Model):
    """
    Message Model - модель сообщения
    title: заголовок сообщения
    body: текст сообщения
    recipient: клиенты
    is_published: опубликовано
    owner: автор сообщения
    """
    title = models.CharField(max_length=150, verbose_name='заголовок сообщения')
    body = models.TextField(verbose_name='текст сообщения')
    recipients = models.ManyToManyField(Client, related_name='recipients', verbose_name='получатели')
    is_published = models.BooleanField(default=False, verbose_name='опубликовано')

    # сообщение принадлежит текущему пользователю:
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='автор сообщения')

    # def clean(self):
    #     if self.is_published and not self.owner:
    #         raise ValidationError('Поле "автор рассылки" обязательно к заполнению.')
    def clean(self):
        if self.is_published and self.owner is None:
            raise ValidationError('Поле "автор сообщения" обязательно к заполнению.')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        permissions = [
            ('can_view_message', 'Can view message'),  # разрешение на просмотр сообщений
        ]


class Mailing(models.Model):
    """
    Mailing Model - модель рассылки
    message: связанное сообщение
    start_time: дата начала рассылки
    end_time: дата окончания рассылки
    frequency: периодичность рассылки
    status: статус рассылки
    """
    ONCE = 'once'
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

    PERIOD_CHOICES = [
        (ONCE, 'Разово'),
        (DAILY, 'Ежедневно'),
        (WEEKLY, 'Еженедельно'),
        (MONTHLY, 'Ежемесячно'),
    ]

    DRAFT = 'draft'
    CREATED = 'created'
    RUNNING = 'running'
    COMPLETED = 'completed'

    STATUS_CHOICES = [
        (DRAFT, 'Черновик'),
        (CREATED, 'Создана'),
        (RUNNING, 'Запущена'),
        (COMPLETED, 'Завершена'),
    ]
    send_name = models.CharField(max_length=255, verbose_name='имя рассылки', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='связанное сообщение')
    start_time = models.DateTimeField(verbose_name='Начало рассылки', **NULLABLE)
    end_time = models.DateTimeField(verbose_name='Окончание рассылки', **NULLABLE)

    frequency = models.CharField(max_length=20, choices=PERIOD_CHOICES,
                                 verbose_name='периодичность', **NULLABLE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=DRAFT,
                              verbose_name='статус рассылки', **NULLABLE)
    # автор рассылки
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='автор рассылки')

    def clean(self):
        # Проверка, что дата окончания больше даты начала
        if self.end_time and self.start_time and self.end_time <= self.start_time:
            raise ValidationError("Дата окончания должна быть больше даты начала.")



    def __str__(self):
        return f'{self.message.title} - {self.start_time}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            ('can_view_mailing', 'Can view mailing'),  # разрешение на просмотр рассылок
            ('can_send_mailing', 'Can send mailing'),  # разрешение на отправку рассылок
            ('can_disable_mailing', 'Can disable mailing'),  # разрешение на отключение рассылок
        ]


class Log(models.Model):
    """
    Log Model: модель логов рассылок
    send_time: время последней попытки
    attempt_status: статус попытки
    server_response: ответ сервера
    mailing: рассылка
    """
    SUCCESS = 'success'
    FAILED = 'failed'

    STATUS_CHOICES = [
        (SUCCESS, 'Успешно'),
        (FAILED, 'Неуспешно'),
    ]

    send_time = models.DateTimeField(auto_now_add=True, verbose_name='время последней попытки', **NULLABLE)
    attempt_status = models.CharField(max_length=15, choices=STATUS_CHOICES, verbose_name='статус попытки', **NULLABLE)
    server_response = models.TextField(max_length=255, verbose_name='ответ сервера', **NULLABLE)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка', **NULLABLE, related_name='mail_logs')

    def __str__(self):
        return f'{self.mailing.message.title} - {self.send_time}'

    def clean(self):
        # Проверка статуса попытки
        if self.attempt_status not in dict(self.STATUS_CHOICES):
            raise ValidationError("Статус попытки должен быть 'success' или 'failed'.")

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'
        ordering = ('attempt_status',)

mailing/forms.py
from django import forms
from django.forms import CheckboxInput

from clients.models import Client
from .models import Message, Mailing


class StyleFormMixin:
    """Миксин для стилизации форм"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class MessageForm(forms.ModelForm):
    """Основная форма создания сообщения рассылки: тема, сообщение, список получателей"""
    recipient = forms.ModelMultipleChoiceField(
        queryset=Client.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-inline'})  # добавьте класс для управления стилем
    )

    # def __init__(self, *args, **kwargs):
    #     user = kwargs.pop('user')
    #     super().__init__(*args, **kwargs)
    #     if user.is_superuser:
    #         self.fields['recipient'].queryset = Client.objects.all()
    #     else:
    #         self.fields['recipient'].queryset = Client.objects.filter(owner=user)

    class Meta:
        model = Message
        fields = ('title', 'body', 'recipient', 'is_published')


class MailingForm(forms.ModelForm):
    """Форма для рассылки: время начала, время окончания, периодичность"""

    class Meta:
        model = Mailing
        fields = ('send_name','message', 'start_time', 'end_time', 'frequency', 'status')
        widgets = {
            'start_time': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'placeholder': 'Введите дату и время начала'
            }),
            'end_time': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'placeholder': 'Введите дату и время окончания'
            }),
        }

mailing/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView

from .forms import MessageForm, MailingForm
from .models import Message, Mailing, Log


class MessageListView(LoginRequiredMixin, ListView):
    """Список сообщений"""
    model = Message
    template_name = 'mailing/message_list.html'
    context_object_name = 'object_list'
    extra_context = {
        'title': 'Список сообщений'
    }

    def get_queryset(self):
        return Message.objects.all()


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Просмотр сообщения"""
    model = Message
    template_name = 'mailing/message_detail.html'
    context_object_name = 'object_list'
    extra_context = {
        'title': 'Просмотр сообщения'
    }


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Создание сообщения"""
    model = Message
    template_name = 'mailing/message_form.html'
    form_class = MessageForm
    extra_context = {
        'title': 'Создание сообщения'
    }
    success_url = reverse_lazy('mailing:message_list')

    def form_valid(self, form):
        """Создаваемое сообщение принадлежит текущему пользователю"""
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование сообщения"""
    model = Message
    template_name = 'mailing/message_form.html'
    form_class = MessageForm
    extra_context = {
        'title': 'Редактирование сообщения'
    }
    success_url = reverse_lazy('mailing:message_list')

    def get_object(self, queryset=None):
        """Редактировать сообщение может только создатель сообщения"""
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404('Вы не можете редактировать это сообщение')
        return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление сообщения"""
    model = Message
    template_name = 'mailing/message_confirm_delete.html'
    extra_context = {
        'title': 'Удаление сообщения'
    }
    success_url = reverse_lazy('mailing:message_list')


class MailingListView(LoginRequiredMixin, ListView):
    """Список рассылок"""
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    context_object_name = 'object_list'
    extra_context = {
        'title': 'Список рассылок'
    }

    def get_queryset(self):
        return Mailing.objects.all()


class MailingDetailView(LoginRequiredMixin, DetailView):
    """Просмотр рассылки"""
    model = Mailing
    template_name = 'mailing/mailing_detail.html'
    context_object_name = 'object_list'
    extra_context = {
        'title': 'Просмотр рассылки'
    }

    def get_object(self, queryset=None):
        """Просмотр рассылки может только создатель рассылки"""
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404('Вы не можете просматривать это рассылку')
        return self.object

    def get_context_data(self, **kwargs):
        """Добавляем логи в контекст"""
        context = super().get_context_data(**kwargs)
        context['logs'] = Log.objects.filter(mailing=self.object).order_by('-send_time')
        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Создание рассылки"""
    model = Mailing
    template_name = 'mailing/mailing_form.html'
    form_class = MailingForm
    extra_context = {
        'title': 'Создание рассылки'
    }
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        """Создаваемая рассылка принадлежит текущему пользователю"""
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование рассылки"""
    model = Mailing
    template_name = 'mailing/mailing_form.html'
    form_class = MailingForm
    extra_context = {
        'title': 'Редактирование рассылки'
    }
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        """Редактировать рассылку может только создатель рассылки"""
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404('Вы не можете редактировать рассылки других пользователей')
        return self.object



class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление рассылки"""
    model = Mailing
    template_name = 'mailing/mailing_confirm_delete.html'
    extra_context = {
        'title': 'Удаление рассылки'
    }
    success_url = reverse_lazy('mailing:mailing_list')

    def test_func(self):
        """Удалить рассылку может суперпользователь"""
        return self.request.user.is_superuser


# @login_required
# def toggle_publish(request, pk):
#     message = get_object_or_404(Message, pk=pk, author=request.user)
#     message.is_published = not message.is_published
#     message.save()
#     return redirect('mailing:message_detail', pk=pk)

class LogListView(LoginRequiredMixin, ListView):
    """Список логов"""
    model = Log
    template_name = 'mailing/log_list.html'
    context_object_name = 'object_list'
    extra_context = {'title': 'Список логов'}

    def get_queryset(self):
        return Log.objects.all()


class LogDetailView(LoginRequiredMixin, DetailView):
    """Просмотр лога"""
    model = Log
    template_name = 'mailing/log_detail.html'
    context_object_name = 'log'
    extra_context = {'title': 'Просмотр лога'}

mailing/templates/mailing/log_detail.html
{% extends 'main/base.html' %}


{% block content %}
    <h1>{{ title }}</h1>
    <table>
        <tr>
            <th>Рассылка</th>
            <th>Время попытки</th>
            <th>Статус</th>
        </tr>
        <tr>
            <td>{{ log.mailing.send_name }}</td>
            <td>{{ log.send_time }}</td>
            <td>{{ log.attempt_status }}</td>
        </tr>
    </table>
{% endblock %}

mailing/templates/mailing/log_list.html
{#{% extends 'main/base.html' %}#}
{##}
{##}
{#{% block content %}#}
{#    <h1>{{ title }}</h1>#}
{#    <table>#}
{#        <tr>#}
{#            <th>Рассылка</th>#}
{#            <th>Время попытки</th>#}
{#            <th>Статус</th>#}
{#            <th></th>#}
{#        </tr>#}
{#        {% for log in object_list %}#}
{#            <tr>#}
{#                <td>{{ log.mailing.send_name }}</td>#}
{#                <td>{{ log.send_time }}</td>#}
{#                <td>{{ log.attempt_status }}</td>#}
{#                <td><a href="{% url 'mailing:log_detail' log.pk %}">Просмотр</a></td>#}
{#            </tr>#}
{#        {% endfor %}#}
{#    </table>#}
{#    <div class="card-footer">#}
{#        <div class="btn-group">#}
{#            <a href="{% url 'mailing:mailing_list' %}" type="button"#}
{#               class="btn btn-sm btn-outline-secondary">К рассылкам</a>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}
{% extends 'main/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Рассылка</th>
                    <th>Время попытки</th>
                    <th>Статус</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for log in object_list %}
                    <tr>
                        <td>{{ log.mailing.send_name }}</td>
                        <td>{{ log.send_time }}</td>
                        <td>{{ log.attempt_status }}</td>
                        <td><a href="{% url 'mailing:log_detail' log.pk %}" class="btn btn-info btn-sm">Просмотр</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <div class="btn-group">
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-sm btn-outline-secondary">К рассылкам</a>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'main/base.html' %}
{% load static %}
{#{% load filters %}#}

{% block content %}
    <div class="row">
    <!-- форма для удаления рассылки -->
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить рассылку "{{ object.send_name }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'mailing:mailing_list' %}" class="btn btn-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
       <!--детальная карточка Рассылки в виде таблицы-->
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card box-shadow h-100">
                    <div class="card-header">
                        <h4 class="card-title text-center">
                            Рассылка: {{ object.send_name |title }}
                        </h4>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Название</td>
                                <td>{{ object.send_name|title }}</td>
                            </tr>
                            <tr>
                                <td>Автор</td>
                                <td>{{ object.owner }}</td>  <!-- Добавлено поле автора -->
                            </tr>
                            <tr>
                                <td>Дата создания</td>
                                <td>{{ object.start_time }}</td>
                            </tr>
                            <tr>
                                <td>Дата окончания</td>
                                <td>{{ object.end_time }}</td>
                            </tr>
                            <tr>
                                <td>Сообщение</td>
                                <td>{{ object.message }}</td>
                            </tr>
                        </table>
                    </div>

                    <div class="card-footer">
                        <div class="btn-group">
                            <a href="{% url 'mailing:mailing_list' %}" type="button"
                               class="btn btn-sm btn-outline-secondary">К рассылкам</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card box-shadow h-100">
                    <div class="card-header">
                        <h4 class="card-title text-center">Логи рассылки</h4>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Время попытки</th>
                                    <th>Статус</th>
                                    <th>Ответ сервера</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for log in object.mail_logs.all %}
                                <tr>
                                    <td>{{ log.send_time }}</td>
                                    <td>{{ log.get_attempt_status_display }}</td>
                                    <td>{{ log.server_response }}</td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="3">Логи отсутствуют.</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                <div class="card-footer">
                        <div class="btn-group">
                            <a href="{% url 'mailing:log_list' %}" type="button"
                               class="btn btn-sm btn-outline-secondary">К списку логов</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <!-- форма для создания карточки рассылки-->
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    {% if object %} <!-- если есть объект -->
                        Редактировать рассылку
                    {% else %} <!-- если нет объекта -->
                        Добавить рассылку
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post">  <!-- не забудь вернуть csrf -->
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %} <!-- если есть объект -->
                                Сохранить
                            {% else %} <!-- если нет объекта -->
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'main/base.html' %}


{% block content %}

     <!-- кнопка добавления рассылки -->
     <div class="container">
        <div class="row">
            {% if user.is_authenticated %}
            <div class="col-12 mb-5">
                <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}">Добавить рассылку</a>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- список всех рассылок -->
{#    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">#}
{#        {% for object in object_list %} <!-- цикл перебирает все рассылки-->#}
            <!-- карточка рассылки в подшаблоне -->
            {% include 'main/includes/inc_mailing_card.html' %}
{#        {% endfor %}#}
{#    </div>#}

{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'main/base.html' %}
{% load static %}
{#{% load filters %}#}

{% block content %}
    <div class="row">
    <!-- форма для удаления сообщения -->
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить сообщение "{{ object.title }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'mailing:message_list' %}" class="btn btn-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'main/base.html' %} <!-- наследуемся от main/base.html -->

{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 mb-5">
                <div class="row">
                     <div class="col-md-6 offset-md-3">
                        <div class="card box-shadow">
                            <div class="card-header">
                                <h3 class="card-title">
                                    Сообщение "{{ object.title }}"
                                </h3>
                            </div>
                            <div class="card-body">
                                <p class="card-text">
                                    {{ object.body }}
                                </p>
                                <p class="card-text text-muted">
                                    Автор: {{ object.owner }} <!-- Отображение имени автора сообщения-->
                                </p>
                            </div>
                            <div class="card-footer">
                                <div class="btn-group">
                                    <a href="{% url 'mailing:message_list' %}" type="button"
                                       class="btn btn-sm btn-outline-secondary">К сообщениям</a>

                                </div>
{#                                <!-- счетчик просмотров отдельного материала -->#}
{#                                Просмотры: {{ object.views_count }}#}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <!-- форма для создания карточки сообщения-->
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    {% if object %} <!-- если есть объект -->
                        Редактировать сообщение
                    {% else %} <!-- если нет объекта -->
                        Добавить сообщение
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post">  <!-- не забудь вернуть csrf -->
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %} <!-- если есть объект -->
                                Сохранить
                            {% else %} <!-- если нет объекта -->
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'main/base.html' %}

{% block content %}
     <!-- Кнопка добавления сообщения -->
    <div class="container">
        <div class="row">
            <div class="col-12 mb-5">
                <a class="btn btn-outline-primary" href="{% url 'mailing:message_create' %}">Добавить сообщение</a>
            </div>
        </div>
    </div>

  <title>Список сообщений</title>
    <!-- карточки сообщений -->
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %} <!-- цикл перебирает все объекты -->
            <!-- карточка клиента в подшаблоне -->
            {% include 'main/includes/inc_message_card.html' %}
        {% endfor %}
    </div>


{% endblock %}