config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),  # путь до приложения main
                  path('clients/', include('clients.urls', namespace='clients')),  # путь до приложения clients
                  path('mailing/', include('mailing.urls', namespace='mailing')),  # путь до приложения mailing
                  path('users/', include('users.urls', namespace='users')),  # путь до приложения users
                  path('vlog/', include('vlog.urls', namespace='vlog')),  # путь до приложения vlog
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexView

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Главная
]

vlog/urls.py
from django.urls import path

from vlog.apps import VlogConfig
from vlog.views import VlogPostCreateView, VlogPostListView, VlogPostDetailView, VlogPostUpdateView, VlogPostDeleteView

app_name = VlogConfig.name


urlpatterns = [
    path('create_post/', VlogPostCreateView.as_view(), name='create_post'),  # создание поста
    path('post_list/', VlogPostListView.as_view(), name='post_list'),  # путь до страницы со всеми постами
    path('edit_post/<int:pk>/', VlogPostUpdateView.as_view(), name='edit_post'),  # редактирование поста
    path('post_detail/<int:pk>/', VlogPostDetailView.as_view(), name='post_detail'),  # карточка поста
    path('delete_post/<int:pk>/', VlogPostDeleteView.as_view(), name='delete_post'),  # удаление поста
]

vlog/models.py
import uuid

from django.conf import settings
from django.db import models
from django.utils.text import slugify

NULLABLE = {'null': True, 'blank': True}


# Create your models here.
class VlogPost(models.Model):
    """Модель поста"""
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    content = models.TextField(blank=True, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='Превью', **NULLABLE)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.PositiveIntegerField(default=0, verbose_name='Просмотры')

    # связь с текущим юзером
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return f'{self.title}'

    def save(self, *args, **kwargs):
        if not self.slug:
            # если значение slug не задано, создаем его на основе заголовка статьи и случайного UUID
            self.slug = slugify(self.title) + '-' + str(uuid.uuid4().hex[:6])
            # проверяем, что значение slug уникально
            while VlogPost.objects.filter(slug=self.slug).exists():
                self.slug = slugify(self.title) + '-' + str(uuid.uuid4().hex[:6])
        super(VlogPost, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-created']
        permissions = [
            ('can_publish', 'Может опубликовать'),
        ]

vlog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from vlog.models import VlogPost


# Create your views here.
class VlogPostCreateView(LoginRequiredMixin, CreateView):
    """Контроллер создания поста"""
    model = VlogPost
    template_name = 'vlog/vlogpost_form.html'
    fields = ('title', 'content', 'preview', 'is_published')
    success_url = reverse_lazy('vlog:post_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Устанавливаем владельца поста
        return super().form_valid(form)


    # def get_object(self, queryset=None):
    #     """Проверяем что пользователь не может редактировать чужой пост"""
    #     self.object = super().get_object(queryset)
    #     if self.object.owner != self.request.user and not self.request.user.is_staff:
    #         raise Http404('Вы не можете редактировать чужую собаку')  # может владелец и модератор
    #     return self.object




class VlogPostUpdateView(LoginRequiredMixin, UpdateView):
    """Контроллер редактирования поста"""
    model = VlogPost
    template_name = 'vlog/vlogpost_form.html'
    fields = ('title', 'content', 'preview', 'is_published')
    # success_url = reverse_lazy('vlog:post_list')




    def get_success_url(self):
        """Перенаправление после редактирования на страницу поста"""
        return reverse('vlog:post_detail', args=[self.kwargs.get('pk')])


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = 'Редактирование поста'
        return context


class VlogPostListView(ListView):
    """Контроллер списка постов"""
    model = VlogPost
    template_name = 'vlog/vlogpost_list.html'
    extra_context = {'title': 'Список постов'}
    paginate_by = 4

    def get_queryset(self):
        """Выводим только опубликованные посты"""

        return VlogPost.objects.filter(is_published=True)


class VlogPostDetailView(LoginRequiredMixin, DetailView):
    """Контроллер просмотра поста"""
    model = VlogPost
    template_name = 'vlog/vlogpost_detail.html'
    extra_context = {'title': 'Просмотр поста'}

    def get_object(self, queryset=None):
        """Метод для счетчика просмотров"""
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object

    def get_queryset(self):
        """Если не owner или staff, то не может просматривать чужой пост"""
        queryset = super().get_queryset()
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset



class VlogPostDeleteView(LoginRequiredMixin, DeleteView):
    """Контроллер удаления поста"""
    model = VlogPost
    template_name = 'vlog/vlogpost_confirm_delete.html'
    success_url = reverse_lazy('vlog:post_list')

vlog/templates/vlog/vlogpost_confirm_delete.html
{% extends 'main/base.html' %}


{% block content %}
    <div class="row">
    <!-- форма для удаления поста -->
    <div class="col-md-6 offset-md-3">
        < <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить пост "{{ object.name }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'vlog:post_list' %}" class="btn btn-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

vlog/templates/vlog/vlogpost_detail.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
        <div class="row">
            <div class="col-6 offset-3">
                <div class="card">

                    <div class="card-header">
                        <h3 class="card-title">
                            Пост "{{ object.title }}" ({{ object.slug }})
                        </h3>
                    </div>

                    <div class="card-body">
                        <p>
                            {{ object.content }}
                        </p>
                    </div>
                    <div class="card-footer d-flex justify-content-between align-items-center">
                        <div>Просмотры: {{ object.view_count }}</div>
                        <div class="btn-group">
                            <a href="{% url 'vlog:post_list' %}"
                               class="btn btn-sm btn-outline-primary">К постам</a>
                              <a  href="{% url 'vlog:edit_post' object.pk %}"
                                class="btn btn-sm btn-outline-secondary">Edit</a>
                                <a  href="{% url 'vlog:delete_post' object.pk %}"
                                    class="btn btn-sm btn-outline-danger">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%  endblock %}

vlog/templates/vlog/vlogpost_form.html
{% extends 'main/base.html' %}

{% block content %}
        <div class="row">

            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {%  if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
{% endblock %}

vlog/templates/vlog/vlogpost_list.html
{% extends 'main/base.html' %}
{% block content %}
    <!--пагинация списка постов начало-->
   {% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item">
      <a class="page-link" href="{% url 'main:index' %}">&laquo; На главную</a>
    </li>
    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
      <a class="page-link" {% if page_obj.has_previous %}href="?page=1"{% endif %}>&laquo; Первая</a>
    </li>
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
      </li>
    {% endif %}
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
      </li>
    {% endif %}
    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
      <a class="page-link" {% if page_obj.has_next %}href="?page={{ paginator.num_pages }}"{% endif %}>&raquo; Последняя</a>
    </li>
{#    <li class="page-item">#}
{#      <a class="page-link" href="{% url 'catalog:product_list' %}">В каталог</a>#}
{#    </li>#}
  </ul>
</nav>
{% endif %}
    <!-- пагинация списка постов конец -->
    <div class="container">
        <div class="row">
            <div class="col-12 mb-5">

               <a class="btn btn-outline-primary" href="{% url 'vlog:create_post' %}">Добавить пост</a>

            </div>
        </div>
    </div>

    <div class="row">
    {% for object in object_list %}
        <div class="col-md-4 mb-3">
            <div class="card box-shadow">
                <div class="card-body">
                    <p class="-text" style="text-align: center; color: black;">
                        {{ object|title }}
                    </p>
                    <p class="card-text">
                        {{ object.content }}
                    </p>

                    <div class="d-flex justify-content-between align-items-center">
                        <p class="text-muted mb-0">Автор: {{ object.owner }}</p>
                        <small class="text-body-secondary mb-0">Просмотры: {{ object.view_count }}</small>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mt-2">  <!-- Flexbox контейнер -->
                        <div class="btn-group me-2">  <!-- Отступ кнопки от статуса -->
                            <a href="{% url 'vlog:post_detail' object.pk %}"
                                class="btn btn-sm btn-outline-primary">View</a>
                        </div>
                        <div class="text-body-secondary">  <!-- Статус публикации -->
                            {% if object %}
                                {% if object.is_published %}
                                    <span style="color: green;">Опубликовано</span>
                                {% else %}
                                    <span style="color: grey;">Не опубликовано</span>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}