clients/urls.py
from django.urls import path

from clients.apps import ClientsConfig
from clients.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, toggle_active, \
    ClientDeleteView

app_name = ClientsConfig.name

urlpatterns = [
    path('client_list/', ClientListView.as_view(), name='client_list'),  # список клиентов
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),  # просмотр клиента
    path('create_client/', ClientCreateView.as_view(), name='create_client'),  # создание клиента
    path('client_edit/<int:pk>/', ClientUpdateView.as_view(), name='client_edit'),  # редактирование клиента
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),  # удаление клиента
    path('active_clients/<int:pk>/', toggle_active, name='active_clients'),  # активация/деактивация клиента
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),  # путь до приложения main
                  path('clients/', include('clients.urls', namespace='clients')),  # путь до приложения clients
                  path('mailing/', include('mailing.urls', namespace='mailing')),  # путь до приложения mailing
                  path('users/', include('users.urls', namespace='users')),  # путь до приложения users
                  path('vlog/', include('vlog.urls', namespace='vlog')),  # путь до приложения vlog
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexView

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Главная
]

clients/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    """
    Client Model - модель клиентов
    email: почта
    first_name: имя
    last_name: фамилия
    comment: Комментарий
    """
    email = models.EmailField(verbose_name='email')
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    comment = models.CharField(max_length=255, verbose_name='комментарий', **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='активный')
    # пользователь, создавший запись о клиенте:
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.first_name} ' \
               f'{self.last_name} ' \
               f'{self.email}'

    class Meta:
        verbose_name = 'клиент рассылки'
        verbose_name_plural = 'клиенты рассылки'
        ordering = ('email',)

clients/forms.py
from django import forms
from django.forms import CheckboxInput

from clients.models import Client


class StyleFormMixin:
    """Миксин для стилизации форм"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    """Форма создания клиента"""
    class Meta:
        model = Client
        # указываю только один из 3 способов заполнения поля
        # fields = '__all__'
        fields = ('email', 'first_name', 'last_name', 'comment')
        # exclude = ('email',)

clients/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from clients.forms import ClientForm
from clients.models import Client


# Create your views here.
class ClientListView(LoginRequiredMixin, ListView):
    """Просмотр списка клиентов"""
    model = Client
    template_name = 'clients/client_list.html'
    extra_context = {
        'title': 'Список клиентов'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # добавление is_owner
        for client in context['object_list']:
            client.is_owner = client.owner == self.request.user
        return context


class ClientDetailView(LoginRequiredMixin, DetailView):
    """Просмотр информации о клиенте"""
    model = Client
    template_name = 'clients/client_detail.html'
    extra_context = {
        'title': 'Информация о клиенте'
    }


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Создание клиента"""
    model = Client
    form_class = ClientForm  # форма для создания клиента
    permission_required = 'clients.add_client'
    template_name = 'clients/client_form.html'
    extra_context = {
        'title': 'Создание клиента'
    }
    success_url = reverse_lazy('clients:client_list')

    def form_valid(self, form):
        """Созданная запись о клиенте принадлежит текущему пользователю"""
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Редактирование клиента"""
    model = Client
    form_class = ClientForm  # форма для редактирования клиента
    permission_required = 'clients.change_client'
    template_name = 'clients/client_form.html'
    extra_context = {
        'title': 'Редактирование клиента'
    }
    success_url = reverse_lazy('clients:client_list')

    def get_object(self, queryset=None):
        """Редактировать можно только свои записи клиентов"""
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404('Вы не можете редактировать чужие записи о клиентах')
        return self.object


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление клиента"""
    model = Client
    template_name = 'clients/client_confirm_delete.html'
    extra_context = {
        'title': 'Удаление клиента'
    }
    success_url = reverse_lazy('clients:client_list')

    def test_func(self):
        """Только суперпользователь может удалять клиентов"""
        return self.request.user.is_superuser


@login_required
def toggle_active(request, pk):
    """Переключение активности клиента FBV"""
    client_item = get_object_or_404(Client, pk=pk)
    if client_item.is_active:
        client_item.is_active = False
    else:
        client_item.is_active = True
    client_item.save()
    return redirect(reverse('clients:client_list'))

clients/templates/clients/client_confirm_delete.html
{% extends 'main/base.html' %}
{% load static %}
{#{% load filters %}#}

{% block content %}
    <div class="row">
    <!-- форма для удаления клиента -->
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить карточку клиента "{{ object.first_name }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'clients:client_list' %}" class="btn btn-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

clients/templates/clients/client_detail.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
       <!--детальная карточка Клиента в виде таблицы-->
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card box-shadow h-100">
                    <div class="card-header">
                        <h4 class="card-title text-center">
                            Клиент: {{ object.first_name |title }} {{ object.last_name |title }}
                        </h4>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Имя </td>
                                <td>{{ object.first_name|title }}</td>
                            </tr>
                        <tr>
                                <td>Фамилия </td>
                                <td>{{ object.last_name|title }}</td>
                            </tr>
                            <tr>
                                <td>Почта </td>
                                <td>{{ object.email }}</td>
                            </tr>
                            <tr>
                                <td>Комментарий </td>
                                <td>{{ object.comment }}</td>
                            </tr>
                            <tr>
                                <td>Владелец карточки: </td>
                                <td>{{ object.owner }}</td>
                            </tr>
                        </table>

                    </div>

                    <div class="card-footer">
                         <div class="d-flex justify-content-between align-items-center">
               <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'clients:client_list' %}" type="button" class="btn btn-sm btn-outline-secondary">К клиентам</a>

                </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

clients/templates/clients/client_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <!-- форма для создания карточки клиента -->
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    {% if object %} <!-- если есть объект -->
                        Редактировать клиента
                    {% else %} <!-- если нет объекта -->
                        Добавить клиента
                    {% endif %}
                </div>
                <div class="card-body">
                    <form method="post">  <!-- не забудь вернуть csrf -->
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %} <!-- если есть объект -->
                                Сохранить
                            {% else %} <!-- если нет объекта -->
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

clients/templates/clients/client_list.html
{% extends 'main/base.html' %}

{% block content %}

     <!-- кнопка добавления клиента -->
     <div class="container">
        <div class="row">
            <div class="col-12 mb-5">

                <a class="btn btn-outline-primary" href="{% url 'clients:create_client' %}">Добавить клиента</a>
            </div>
        </div>
    </div>
    <!-- карточки клиентов -->
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %} <!-- цикл перебирает все объекты -->
            <!-- карточка клиента в подшаблоне -->
            {% include 'main/includes/inc_client_card.html' %}
        {% endfor %}
    </div>

{% endblock %}