clients/urls.py
from django.urls import path

from clients.apps import ClientsConfig
from clients.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, toggle_active, \
    ClientDeleteView

app_name = ClientsConfig.name

urlpatterns = [
    path('client_list/', ClientListView.as_view(), name='client_list'),  # список клиентов
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),  # просмотр клиента
    path('create_client/', ClientCreateView.as_view(), name='create_client'),  # создание клиента
    path('client_edit/<int:pk>/', ClientUpdateView.as_view(), name='client_edit'),  # редактирование клиента
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),  # удаление клиента
    path('active_clients/<int:pk>/', toggle_active, name='active_clients'),  # активация/деактивация клиента
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),  # путь до приложения main
                  path('clients/', include('clients.urls', namespace='clients')),  # путь до приложения clients
                  path('mailing/', include('mailing.urls', namespace='mailing')),  # путь до приложения mailing
                  path('users/', include('users.urls', namespace='users')),  # путь до приложения users
                  path('vlog/', include('vlog.urls', namespace='vlog')),  # путь до приложения vlog
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path


from mailing.apps import MailingConfig
from mailing.views import MessageListView, MessageCreateView, MessageUpdateView, MessageDetailView, MessageDeleteView, \
    MailingListView, MailingCreateView, MailingDetailView, MailingUpdateView, MailingDeleteView, LogListView, \
    LogDetailView

app_name = MailingConfig.name


urlpatterns = [
    path('message_list/', MessageListView.as_view(), name='message_list'),  # список сообщений
    path('message_detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),  # просмотр сообщения
    path('message_create/', MessageCreateView.as_view(), name='message_create'),  # создание сообщения
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),  # редактирование сообщения
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),  # удаление сообщения
    # path('message_publish/<int:pk>/toggle_publish/', toggle_publish, name='toggle_publish'),  # публикация сообщения

    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),  # список рассылок
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),  # просмотр рассылки
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),  # создание рассылки
    path('mailing_edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),  # редактирование рассылки
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),  # удаление рассылки

    path('log_list/', LogListView.as_view(), name='log_list'),  # список логов
    path('log_detail/<int:pk>/', LogDetailView.as_view(), name='log_detail'),  # просмотр лога

]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexView

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Главная
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, EmailConfirmSentView, UserConfirmEmailView, \
    EmailConfirmedView, EmailConfirmFailedView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(), name='login'),  # маршрут для входа
    path('logout/', LogoutView.as_view(), name='logout'),  # маршрут для выхода
    path('register/', RegisterView.as_view(), name='register'),  # маршрут для регистрации
    path('profile/', UserUpdateView.as_view(), name='profile'),  # маршрут для профиля
    path('email-confirmation-sent/', EmailConfirmSentView.as_view(), name='email_confirmation_sent'),  # письмо активации отправлено
    path('email-confirmation/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='email_confirmation'),  # активация
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),  # подтверждено
    path('email-confirm-failed/', EmailConfirmFailedView.as_view(), name='email_confirm_failed'),  # неподтверждено

]

vlog/urls.py
from django.urls import path

from vlog.apps import VlogConfig
from vlog.views import VlogPostCreateView, VlogPostListView, VlogPostDetailView, VlogPostUpdateView, VlogPostDeleteView

app_name = VlogConfig.name


urlpatterns = [
    path('create_post/', VlogPostCreateView.as_view(), name='create_post'),  # создание поста
    path('post_list/', VlogPostListView.as_view(), name='post_list'),  # путь до страницы со всеми постами
    path('edit_post/<int:pk>/', VlogPostUpdateView.as_view(), name='edit_post'),  # редактирование поста
    path('post_detail/<int:pk>/', VlogPostDetailView.as_view(), name='post_detail'),  # карточка поста
    path('delete_post/<int:pk>/', VlogPostDeleteView.as_view(), name='delete_post'),  # удаление поста
]

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView

from clients.models import Client
from mailing.models import Mailing, Message
from vlog.models import VlogPost


class IndexView(LoginRequiredMixin, TemplateView):
    """Представление главной страницы."""
    template_name = 'main/index.html'
    extra_context = {
        'title': 'Главная страница',
    }

    def get_context_data(self, **kwargs):
        """Добавляем количество уникальных и активных клиентов в контекст."""
        context = super().get_context_data(**kwargs)

        # Подсчитываем уникальных клиентов
        unique_clients_count = Client.objects.values('email').distinct().count()
        context['unique_clients_count'] = unique_clients_count

        # Подсчитываем активных клиентов
        active_clients_count = Client.objects.filter(is_active=True).count()
        context['active_clients_count'] = active_clients_count

        # Подсчитываем общее количество рассылок
        total_mailings_count = Mailing.objects.count()
        context['total_mailings_count'] = total_mailings_count

        # Подсчитываем проведенные рассылки (например, статус "завершена" или "запущена")
        conducted_mailings_count = Mailing.objects.filter(status__in=['completed', 'running']).count()
        context['conducted_mailings_count'] = conducted_mailings_count

        # Последние 3 сообщения
        context['last_messages'] = Message.objects.order_by('-id')[:3]  # id увеличивается с каждым сообщением

        # Последние 3 рассылки
        context['last_mailings'] = Mailing.objects.order_by('-id')[:3]  # id увеличивается

        # Последние 3 активных клиента (созданных пользователем, например, с полем owner)
        context['last_active_clients'] = Client.objects.filter(is_active=True).order_by('-id')[:3]

        # 3 случайных поста
        context['posts'] = VlogPost.objects.order_by('-id')[:3]

        return context

main/templates/main/includes/inc_client_card.html
{% load static %}
{#{% load filters %}#}

<!-- карточка -->

<div class="col">
    <div class="card shadow-sm">

        <div class="card-body">
            <p class="card-text">
                {% if object.first_name %}
                    {{ object.first_name|title }} <!-- имя с большой буквы -->
                {% endif %}

                {% if object.last_name %}
                    {{ object.last_name|title }} <br><!-- фамилия с большой буквы -->
                {% endif %}

                {% if object.email %}
                    {{ object.email|lower }} <!-- почта с маленькой буквы -->
                {% endif %}
                <!-- Информация о пользователе, создавшем запись -->
                <br>
                {% if object.owner %}
                    Кем создана запись: {{ object.owner }} <!-- имя пользователя -->
                {% else %}
                    Кем создана запись: Неизвестно
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'clients:client_detail' object.pk %}" class="btn btn-sm
                        {% if object.is_active %} btn-outline-primary
                        {% else %} btn-outline-secondary
                        {% endif %}">View</a>
                    {% if object.owner == user or user.is_superuser %}
                    <a href="{% url 'clients:client_edit' object.pk %}" class="btn btn-sm
                        {% if object.is_active %} btn-outline-primary
                        {% else %} btn-outline-secondary
                        {% endif %}">Edit</a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a href="{% url 'clients:client_delete' object.pk %}" class="btn btn-sm
                        {% if object.is_active %} btn-outline-primary
                        {% else %} btn-outline-secondary
                        {% endif %}">Delete</a>
                    {% endif %}
                    {% if object.owner == user or user.is_superuser %}
                        {% if object.is_active %}
                            <a href="{% url 'clients:active_clients' object.pk %}"
                               class="btn btn-sm btn-outline-secondary">Deactivate</a>
                        {% else %}
                            <a href="{% url 'clients:active_clients' object.pk %}"
                               class="btn btn-sm btn-outline-primary">Activate</a>
                        {% endif %}
                    {% endif %}
                </div>
                <small class="text-body-secondary" id="availabilityText">
                    {% if object %}
                        {% if object.is_active %} <!-- активный клиент зеленого цвета -->
                            <span style="color: green;">Активный</span>
                        {% else %} <!-- не активный клиент серого цвета -->
                            <span style="color: grey;">Не активный</span>
                        {% endif %}
                    {% endif %}
                </small>
            </div>
        </div>
    </div>
</div>

main/templates/main/includes/inc_mailing_card.html
{#{% load static %}#}
{#{% load filters %}#}
{##}
{#<!-- карточка рассылки-->#}
{##}
{#<div class="col">#}
{#    <div class="card shadow-sm">#}
{##}
{#        <div class="card-body">#}
{#            <p class="card-text">#}
{#                {{ object.send_name }}  <!-- тема рассылки -->#}
{#            </p>#}
{#            <p class="card-text text-muted">#}
{#                Автор: {{ object.owner }} <!-- Отображение имени автора -->#}
{#            </p>#}
{#            <div class="d-flex justify-content-between align-items-center">#}
{#                <div class="btn-group">#}
{#                    <a href="{% url 'mailing:mailing_detail' object.pk %}" class="btn btn-sm#}
{#                        {% if object.status == 'draft' %} btn-outline-secondary#}
{#                        {% else %} btn-outline-primary#}
{#                        {% endif %}">View</a>#}
{#                    <a href="{% url 'mailing:mailing_edit' object.pk %}" class="btn btn-sm#}
{#                         {% if object.status == 'draft' %} btn-outline-secondary#}
{#                        {% else %} btn-outline-primary#}
{#                        {% endif %}">Edit</a>#}
{##}
{#                    <a href="{% url 'mailing:mailing_delete' object.pk %}" class="btn btn-sm#}
{#                         {% if object.status == 'draft' %} btn-outline-secondary#}
{#                        {% else %} btn-outline-primary#}
{#                        {% endif %}">Delete</a>#}
{#                </div>#}
{#                <small class="text-body-secondary" id="availabilityText">#}
{#                    {% if object and object.status %}#}
{#                        {% if object.status == 'running' %}#}
{#                            <span style="color: green;">Запущена</span>#}
{#                        {% elif object.status == 'completed' %}#}
{#                            <span style="color: gray;">Завершена</span>#}
{#                        {% elif object.status == 'created' %}#}
{#                            <span style="color: gray;">Создана</span>#}
{#                        {% elif object.status == 'draft' %}#}
{#                            <span style="color: orange;">Черновик</span>#}
{#                        {% endif %}#}
{#                    {% endif %}#}
{#                </small>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{# <!-- сверху закоментирована версия рассылок в виде карточек, пусть будет, может пригодится-->#}
{#<!-- внизу карточка рассылок в виде таблицы:-->#}
{% load static %}
{#{% load filters %}#}

<!-- таблица рассылок-->
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Тема рассылки</th>
                <th>Автор</th>
                <th>Статус</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.send_name }}</td>
                    <td>{{ object.owner }}</td>
                    <td>
                        {% if object and object.status %}
                            {% if object.status == 'running' %}
                                <span style="color: green;">Запущена</span>
                            {% elif object.status == 'completed' %}
                                <span style="color: gray;">Завершена</span>
                            {% elif object.status == 'created' %}
                                <span style="color: gray;">Создана</span>
                            {% elif object.status == 'draft' %}
                                <span style="color: orange;">Черновик</span>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td>
                        <div class="btn-group">
                            <a href="{% url 'mailing:mailing_detail' object.pk %}" class="btn btn-sm
                                {% if object.status == 'draft' %} btn-outline-secondary
                                {% else %} btn-outline-primary
                                {% endif %}">View</a>
                            <a href="{% url 'mailing:mailing_edit' object.pk %}" class="btn btn-sm
                                 {% if object.status == 'draft' %} btn-outline-secondary
                                {% else %} btn-outline-primary
                                {% endif %}">Edit</a>
                            <a href="{% url 'mailing:mailing_delete' object.pk %}" class="btn btn-sm
                                 {% if object.status == 'draft' %} btn-outline-secondary
                                {% else %} btn-outline-primary
                                {% endif %}">Delete</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

main/templates/main/includes/inc_main_menu.html
<!-- templates/includes/inc_main_menu.html  -->
<div class="col-sm-4 offset-md-1 py-4">
    <h4>Меню</h4>
    <ul class="list-unstyled">
        <li><a href="{% url 'main:index' %}" class="text-white">Главная</a></li>
        <li><a href="{% url 'clients:client_list' %}" class="text-white">Клиенты</a></li>
        <li><a href="{% url 'mailing:message_list' %}" class="text-white">Сообщения</a></li>
        <li><a href="{% url 'mailing:mailing_list' %}" class="text-white">Рассылки</a></li>
        <li><a href="{% url 'mailing:log_list' %}" class="text-white">Логи</a></li>
        <li><a href="{% url 'vlog:post_list' %}" class="text-white">Блог</a></li>


        {% if user.is_authenticated %}
            <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
            <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
            <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
        {% endif %}


    </ul>
</div>
<!-- Главное меню конец -->

main/templates/main/includes/inc_message_card.html
{% load static %}
{#{% load filters %}#}

<!-- карточка сообщения-->

<div class="col">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">
                {{ object.title|title }}  <!-- заголовок сообщения c заглавной буквы -->
            </p>
            <p class="card-text text-muted">
                Автор: {{ object.owner }} <!-- Отображение имени автора -->
            </p>

            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'mailing:message_detail' object.pk %}" class="btn btn-sm
                        {% if object.is_published %} btn-outline-primary
                        {% else %} btn-outline-secondary
                        {% endif %}">View</a>

                     <a href="{% url 'mailing:message_edit' object.pk %}" class="btn btn-sm
                        {% if object.is_published %} btn-outline-primary
                        {% else %} btn-outline-secondary
                        {% endif %}">Edit</a>

                    <a href="{% url 'mailing:message_delete' object.pk %}" class="btn btn-sm
                        {% if object.is_active %} btn-outline-primary
                        {% else %} btn-outline-secondary
                        {% endif %}">Delete</a>
                </div>
                <small class="text-body-secondary" id="availabilityText">
                    {% if object %}
                        {% if object.is_published %} <!-- опубликованная рассылка зеленого цвета -->
                            <span style="color: green;">Опубликовано</span>
                        {% else %} <!-- не опубликованная рассылка серого цвета -->
                            <span style="color: grey;">Не опубликовано</span>
                        {% endif %}
                    {% endif %}
                </small>
            </div>
        </div>
    </div>
</div>